## Data Analyst
- people who know SQL
- hired by MNC companies as Developers
- Use powerBI -> build charts/graphs
- insights from data
- create charts and graphs to show higher ups(CEO)
- get data that data scientists ask for
- One shot query

## Data Scientist
- provide more insights from the insights
- they will make predicitions using the insights
- they also have to clean the data
- used an Excel sheet
- Python - numpy, pandas
- scale -millions of rows
- data predictions: Scikit
- Matplot, seaborn -Charts
- Line by line (Step)

In [1]:
import numpy as np

## Numpy
- Good with working with arrays(1D)
- Performant (compared Python List)
- C language
- Statistical oriented- mean, median, mode

In [2]:
marks1=[90,80,20,40]
print(marks1 *2)

[90, 80, 20, 40, 90, 80, 20, 40]


In [3]:
marks2= np.array([90,80,20,40])
print(marks2*2)

[180 160  40  80]


## Python way to double the list

In [4]:
marks_dbl=[mark * 2 for mark in marks1]
marks_dbl

[180, 160, 40, 80]

In [ ]:
np.ones(10)
np.ones(100)

# Identity matrix

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Array of 20 5's
fives =5*np.ones(20)  #( use list of same number by using ones and multiplying it with wanted number )
fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5.])

In [11]:
np.arange(10) # a stands for array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Task: 1->10
np.arange(1,11)

In [ ]:
np.arange(1, 11 ,2) # use skip to get odd/even


array([1, 3, 5, 7, 9])

## Operations
- normal operations:
    1. multipication
    2. division
    3. subtraction
    4. addition
- Boolean(matrix/mask)

In [ ]:
np.arange(1,11) * 2 # times all numbers in range

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [14]:
np.arange(1, 11) / 2


array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [15]:
np.arange(1, 11) + 2


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
np.arange(1, 11) - 2


array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [ ]:
np.arange(1, 11) + np.arange(1, 11)
# each element will be added up

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [21]:
np.array([9,2,3]) + np.array([1,2,5]) # Metrix addition

array([10,  4,  8])

In [ ]:
[9,2,3]+[1,2,3]   #concatenates two arrays

[9, 2, 3, 1, 2, 3]

In [ ]:
np.arange(1,11)>5 ## True or false of value>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [25]:
first_ten_nums= np.arange(1,11)
only_five_bm= first_ten_nums>5
first_ten_nums[only_five_bm]

array([ 6,  7,  8,  9, 10])

In [26]:
nums= np.array([5,6,6,7,8,9,10,2,5,1])
bm= np.arange(1,11)>5
print(nums[bm])

[ 9 10  2  5  1]


In [34]:
#1.1 Task :with skips
# 1-200 even numbers
np.arange(0,201,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200])

In [35]:
# Task 1.2
# 1-200 only even numbers | Dont use skip of arange
nums= np.arange(1,201)
bm= np.arange(1,201) %2==0
print(nums[bm])

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198 200]


In [40]:
nums=np.arange(1,201)
nums[nums%2==0]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

In [36]:
np.array([9,2,3]) - np.array([6,2,5])

array([ 3,  0, -2])

In [ ]:
np.array([9,2,3]) - np.array([6,2,5,7]) #cant't perform operations on arrays/metrix with different sizes/lenghts

array([531441,      4,    243])

In [ ]:
np.array([9, 2, 3]) ** np.array([3, 2, 5])
#powers each number in array based on second array number in same index

array([729,   4, 243])

## CREATE ARRAYS
-ones
array()
np.arange

In [43]:
ages=np.random.randint(18,60,5)   #(from:to, how many numbers)
print(ages)
ages_list=ages.tolist()
print(ages_list)


[20 45 18 29 20]
[20, 45, 18, 29, 20]


In [47]:
ages = np.random.randint(18, 60, 50)
print(ages)
ages[ages>25]

[24 40 51 31 56 58 48 22 19 34 50 19 52 53 52 30 24 56 50 59 27 36 33 56
 43 47 30 46 56 45 21 41 39 56 36 34 45 44 37 42 18 51 34 58 49 44 26 59
 38 40]


array([40, 51, 31, 56, 58, 48, 34, 50, 52, 53, 52, 30, 56, 50, 59, 27, 36,
       33, 56, 43, 47, 30, 46, 56, 45, 41, 39, 56, 36, 34, 45, 44, 37, 42,
       51, 34, 58, 49, 44, 26, 59, 38, 40], dtype=int32)

In [49]:
%%time
ages_list

CPU times: total: 0 ns
Wall time: 0 ns


[20, 45, 18, 29, 20]

In [50]:
ages=np.random.randint(18,60,500_00)
age_list= ages.tolist()
print(ages_list)

[20, 45, 18, 29, 20]


In [57]:
%%time
ages_list = [age * 2 for age in ages_list]


CPU times: total: 0 ns
Wall time: 0 ns


## Performance
-numpy arrays are 100-1000 times the performance of python list
-%%time -time operation